### ISSUE TITLE
[Dipendenza esterna] Upgrade e gestione aggiornamenti - OpenSSL

### ISSUE THREAD

**Issue by gvarisco** [italia/cie-middleware#1]
> Il progetto CSP ha un’unica dipendenza esterna a OpenSSL, versione 1.0.0d, a 32 e 64 bit. La libreria viene linkata staticamente, quindi non è necessaria la presenza delle librerie a runtime.

Dobbiamo:

- Assicurarci che nel momento del rilascio il tutto venga testato linkando staticamente OpenSSL ad una versione supportata.
- Vi sia una procedura di upgrade del binario che aggiorni in maniera corretta anche le dipendenze esterne (linkate staticamente)

Da https://www.openssl.org/source/:
> Note: The latest stable version is the 1.1.0 series of releases. Also available is the 1.0.2 series. This is also our Long Term Support (LTS) version (support will be provided until 31st December 2019). The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be us

Da https://www.openssl.org/policies/releasestrat.html (Release Strategy):

> Version 1.1.0 will be supported until 2018-08-31.
> Version 1.0.2 will be supported until 2019-12-31 (LTS).
> Version 1.0.1 is no longer supported.
> Version 1.0.0 is no longer supported.
> Version 0.9.8 is no longer supported.

**Comment by madduci** [comment]
Si potrebbe usare [conan.io](https://www.conan.io/) per gestire il progetto e le sue dipendenze. Si aggiungerebbe python come linguaggio di scripting, ma si avrebbe il vantaggio di render il tutto portabile anche su linux e mac. Magari poi passando dai VisualStudio .sln a CMake, si potrebbe aver il vantaggio di usare il compilatore che si desidera (VS2013, 2015 o 2017), oltre che si renderebbe facile creare un file di setup (MSI o EXE) in modo automatico

**Comment by alexrj** [comment]
In #49 è stata rimossa la dipendenza da OpenSSL, sostituita da BCrypt.
