### ISSUE TITLE
@Sivi17 Con CIE rilasciata il 06.10.2021 la versione CIE Middleware 1.3.3.1 funziona. Accoppiata CIE correttamente e loggato a fascicolo Sanitario Regione Lombardia, INPS e portale ANPR del cittadino

### ISSUE THREAD

**Issue by japita-se** [italia/cie-middleware#100]
@Sivi17 Con CIE rilasciata il 06.10.2021 la versione CIE Middleware 1.3.3.1 funziona. Accoppiata CIE correttamente e loggato a fascicolo Sanitario Regione Lombardia, INPS e portale ANPR del cittadino

_Originally posted by @cvignati in https://github.com/italia/cie-middleware/issues/94#issuecomment-942498141_

Confermo che la versione 1.4.1.0 su alcuni sistemi Windows 10 non funziona (sembra che manchi qualche file).

**Comment by aantetomaso** [comment]
Prego far riferimento a questa issue:

https://github.com/italia/cie-middleware/issues/98
