### ISSUE TITLE
1.4.2.0 elimina ciepki.

### ISSUE THREAD

**Issue by anunasica** [italia/cie-middleware#102]
Leggendo questo post (l'ultimo della pagina) https://forum.italia.it/t/errore-installazione-software-cie-1-4-0/23992
mi ha riportato alla mente la mia esperienza: l'installazione della versione 1.4.2.0 avvenuta l'8 dicembre ha comportato la cancellazione definitiva di ciepki.dll in system32. Molto meravigliato, ma ho risolto disinstallando e reinstallando e pare tutto bene, ho effettuato registrazione e accesso. Oggi dal 3d citato scopro che questo malfunzionamento affligge anche altri. Potete controllare? grazie e buon anno!

**Comment by anunasica** [comment]
Segnalo che avevo preventivamente disinstallato la vecchia versione 1.4.1.0 ma che non mi era concesso disabbinare (de-registrare?) la carta e questo può essere pericoloso se si convidide il dispositivo.

**Comment by anunasica** [comment]
Dopo ulteriori prove, approfittando della necessità di cambiare laptop (w10), confermo che è impossibile disconnettere la CIE dal Middleware. Sperando che la disinstallazione sia sufficiente, altrimenti in caso di laptop condiviso la situazione è grave.

**Comment by anunasica** [comment]
c'è qualcuno in ascolto?

**Comment by aantetomaso** [comment]
Disinstallando il Software CIE vengono rimosse le carte abbinate ad esso e rimossa anche la CIEPKI.dll, ovvero l'interfaccia PKCS#11 che fa parte del pacchetto. E' una scelta di implementazione, altrimenti si avrebbe una disinstallazione incompleta.
Si può essere più precisi sulla issue e su cosa va corretto?

**Comment by anunasica** [comment]
Gentilissimo, grazie, allora è giusto così.

**Comment by aantetomaso** [comment]
Perfetto, chiudo la issue. Grazie.
