### ISSUE TITLE
C++ redistributable ANCORA necessario

### ISSUE THREAD

**Issue by anunasica** [italia/cie-middleware#105]
Nonostante https://githubhot.com/repo/italia/cie-middleware/issues/98
oggi, dopo aggiornamenti Windows10, sono stato costretto a reinstallare il pacchetto Redistributable C++ 2015-2022. Curioso.

**Comment by forart** [comment]
Suggerimento (per chi ha i privilegi di amministrazione): installate quest'AIO !

https://github.com/abbodi1406/vcredist

**Comment by avagraha** [comment]
C'ė qualcuno o il progetto è morto?

**Comment by aantetomaso** [comment]
La issue è risolta nella release 1.4.3.1
