### ISSUE TITLE
problema con app citrix o altre

### ISSUE THREAD

**Issue by Mcgreygor** [italia/cie-middleware#113]
Ciao ragazzi, volevo solo dirvi che dopo diverse madonne, sono riuscito a farlo funzionare xD
ho scoperto che ci sono diversi programmi che possono dare fastidio lato driver alle periferiche.
-anydesk
-teamviewer (o qualsiasi software di condivisione schermo)
-citrix receiver
-citrix workspace

lo so che non essendo riproducibile il problema, non riuscite a capire cosa succede, però quantomeno se qualcuno vi rompe, ditegli di provare a disinstallare uno di questi programmi.
ho fatto un reddit  https://www.reddit.com/r/ItalyInformatica/comments/xlalwl/attivazione_spid_o_altro_con_cie/

**Comment by aantetomaso** [comment]
Grazie mille.
