### ISSUE TITLE
SIGSEGV Dopo Inserimento PIN Su Ubuntu 22.04

### ISSUE THREAD

**Issue by montaltoalessandro** [italia/cie-middleware#117]
cari tutti,

ho installato cie middleware su Ubuntu 22.04. All'inizio l'installazione è andata a buon fine, ma quando ho provato a lanciarlo da terminale perché da icona nella lista delle app non partiva, ho notato un errore con openjdk-11-jdk che ho risolto lanciando il comando sudo apt install openjdk-11-jdk.

Il programma adesso parte, ma dopo l'inserimento del pin ottengo il seguente errore

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdf7590eaf8, pid=7702, tid=7862
#
# JRE version: OpenJDK Runtime Environment (11.0.17+8) (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [jna5155634425831493204.tmp+0xeaf8]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/ale/core.7702)
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xms1G -Xmx1G -Djna.library.path=.:/usr/local/lib it.ipzs.cieid.MainApplication

Host: AMD Ryzen 7 5800X 8-Core Processor, 16 cores, 62G, Ubuntu 22.04.1 LTS
Time: Thu Nov 17 10:27:54 2022 CET elapsed time: 44.640502 seconds (0d 0h 0m 44s)

---------------  T H R E A D  ---------------

Current thread (0x00007fdf8015a800):  JavaThread "Thread-0" [_thread_in_native, id=7862, stack(0x00007fdfec000000,0x00007fdfec100000)]

Stack: [0x00007fdfec000000,0x00007fdfec100000],  sp=0x00007fdfec0fce70,  free space=1011k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jna5155634425831493204.tmp+0xeaf8]
C  [libffi.so.8+0x77ec]
C  [libffi.so.8+0x8050]
C  [libffi.so.8+0x7e2e]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokeInt(JI[Ljava/lang/Object;)I+0
j  com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;Z)Ljava/lang/Object;+225
j  com.sun.jna.Function.invoke(Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+262
j  com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+316
j  com.sun.proxy.$Proxy0.AbilitaCIE(Ljava/lang/String;Ljava/lang/String;[ILit/ipzs/cieid/Middleware$ProgressCallBack;Lit/ipzs/cieid/Middleware$CompletedCallBack;)I+34
j  it.ipzs.cieid.MainFrame$64.run()V+33
j  java.lang.Thread.run()V+11 java.base@11.0.17
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000000bb

Register to memory mapping:

RAX=0x00007fdf7590eac0: <offset 0x000000000000eac0> in /tmp/jna-96666/jna5155634425831493204.tmp at 0x00007fdf75900000
RBX=0x00007fdfec0fcec8 is pointing into the stack for thread: 0x00007fdf8015a800
RCX=0x000000000000003b is an unknown value
RDX=0x00007fdfec0fcf10 is pointing into the stack for thread: 0x00007fdf8015a800
RSP=0x00007fdfec0fce70 is pointing into the stack for thread: 0x00007fdf8015a800
RBP=0x00007fdfec0fcf00 is pointing into the stack for thread: 0x00007fdf8015a800
RSI=0x00007fdfec0fcec8 is pointing into the stack for thread: 0x00007fdf8015a800
RDI=0x00007fdf48124428 points into unknown readable memory: 0x0000000200000002 | 02 00 00 00 02 00 00 00
R8 =0x00007fdfec0fcfe0 is pointing into the stack for thread: 0x00007fdf8015a800
R9 =0x0000000000000002 is an unknown value
R10=0x0 is NULL
R11=0xec2295f08a1d4862 is an unknown value
R12=0x00007fdfce600340: ffi_type_pointer+0x0000000000000000 in /lib/x86_64-linux-gnu/libffi.so.8 at 0x00007fdfce5f7000
R13=0x0000000000000002 is an unknown value
R14=0x00007fdf48119980 points into unknown readable memory: 0x00007fdfce6003d0 | d0 03 60 ce df 7f 00 00
R15=0x000000000000003b is an unknown value
...

Mi potete dare una mano a risolvere il problema cortesemente?

E' utile che vi alleghi tutto il file hs_err_pid...log?

Grazie mille in anticipo,

un caro saluto,

a presto,

Ale

**Comment by matteof04** [comment]
Io avevo lo stesso problema. Ho risolto installando java 17 direttamente dai repository di ubuntu.

**Comment by montaltoalessandro** [comment]
ciao @matteof04, grazie mille per la tua risposta. Ho fatto anche quello che dici, ma purtroppo non risolve il problema :( hai altri suggerimenti?

Grazie mille in anticipo,

Ale

**Comment by matteof04** [comment]
Hai controllato che Java 17 sia effettivamente in uso? Puoi usare il comando `java --version`. Oltre a questo, dopo aver riscontrato il problema io ho installato Java 17 da apt e CIE Middleware dal file tar.gz anziché dal file deb. Forse è nel pacchetto il problema

**Comment by montaltoalessandro** [comment]
aaahhh ecco. Allora, appena posso, faccio il controllo per vedere se effettivamente Java 17 è in uso, poi provo a disinstallare CIE Middleware perché l'ho installato da file .deb. Io non essendo un esperto, trovo un po' difficile installare da tar.gz. Mica mi puoi dire un secondo che comandi usare per installare da tar.gz o mi riferisci ad una risorsa che lo spiega per bene? Ho trovato [questa](https://askubuntu.com/questions/25961/how-do-i-install-a-tar-gz-or-tar-bz2-file), ma è vecchia di 11 anni. E' ancora perfettamente valida secondo te?

Grazie mille ancora :) Gentilissimo

Ale

**Comment by matteof04** [comment]
In fondo a [questa](https://www.cartaidentita.interno.gov.it/fornitori-di-servizi/documentazione-middleware-cie/) pagina c'è il manuale d'uso ufficiale per Linux che contiene anche la procedura di installazione. Io ho usato quella. C'è anche una guida per l'uso con Firefox. Purtroppo però Firefox su Ubuntu 22.04 è installato di default da Snap, che darà un errore al momento dell'aggiunta del certificato. L'unico modo è reinstallare Firefox da apt anziché da Snap store.

**Comment by montaltoalessandro** [comment]
ok, io uso brave che è basato su chrome. Quindi devo anche installare firefox da apt...proverò dai. Grazie mille davvero. Se chiudo la issue, poi eventualmente posso riaprirla? In questo modo non lascio cose in sospeso perché non so quando posso collegarmi sul pc mio dove ho ubuntu.

**Comment by matteof04** [comment]
Penso sia possibile usare la CIE anche su Brave, ma la procedura sarà leggermente diversa. L'importante è che non sia installato via Snap, che sembra creare problemi. Le issue si possono anche riaprire, e forse si può scrivere al loro interno anche se sono chiuse.

**Comment by montaltoalessandro** [comment]
In attesa di feedback dopo che ho implementato i suggerimenti di @matteof04

**Comment by montaltoalessandro** [comment]
purtroppo @matteof04 ho fatto come mi hai detto ma ancora non funziona. Dopo java --version ottengo

openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)

Ho installato il CIE middleware da tar.gz copiando i file estratti nelle path the scrivono sul manuale ufficiale. Il problema è che se faccio doppio clic sull'icona CIE dal menu delle applicazioni si apre la finestra dove digito il pin, clicco su abbina e il programma crasha.

Se apro il programma andando nella cartella usr/share/CIEID e lanciando il comanda java -jar cieid.jar dopo aver inserito il pin e cliccato su abbina il programma non va avanti. La barra di caricamento resta grigia.

Sapresti darmi una mano al riguardo?

Grazie mille ancora,

Ale

**Comment by matteof04** [comment]
Prima di lanciare il programma da terminale prova ad inserire `export LD_LIBRARY_PATH=/usr/local/lib`. Probabilmente va ugualmente in crash, ma almeno vediamo il motivo.

**Comment by montaltoalessandro** [comment]
Ciao @matteof04 grazie mille per la tua risposta. Quindi, se ho capito bene, prima lancio il comando export LD_LIBRARY_PATH=/usr/local/lib e poi il comando java -jar cieid.jar, giusto?

**Comment by matteof04** [comment]
Esatto

**Comment by montaltoalessandro** [comment]
ecco qua

File INI:/usr/local/lib/ciepki.ini
Inizio Sessione - versione: Sep 15 2022 17:10:03Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
^Cdouble free or corruption (fasttop)
Aborted (core dumped)

**Comment by aantetomaso** [comment]
Chiudo per errato repository. Prego riaprire issue, se ancora presente su https://github.com/italia/cie-middleware-linux
