### ISSUE TITLE
Crash di Mozilla Firefox con build superiori alla 90

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware#119]
Le versioni di Firefox dalla 90 in poi vanno in crash dopo l'immissione del PIN.

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.4

**Comment by p060477** [comment]
non risolta con l'ultima 1.4.3-12......
vedi:
https://github.com/italia/cie-middleware/issues/169#issue-3778565040
