### ISSUE TITLE
Errore nello script e Verfica aggiornamenti

### ISSUE THREAD

**Issue by anunasica** [italia/cie-middleware#121]
Salve,
1) cliccando su Tutorial o Aiuto o Informazioni si perviene a questo errore 
https://postimg.cc/rDPyhD0K

Accettando con "Sì" poi funziona; non grave, è solo un fastidio.

2) Dal nuovo manuale apprendo che questa app funziona fino a w10; se migrassi sul nuovo w11 non funzionerebbe?

3) Non sono mai riuscito a far funzionare "Verifica aggiornamenti" dal menù a tendina di w10 (Avvio): pare che non si riesca a stabilire una connessione col server.

Grazie e complimenti, in generale sono molto contento.
Saluti.

**Comment by marzialerosi** [comment]
ciao

1. succede anche a me su win 11 ma l'app funziona
2. funziona su win 11 benissimo

solo che ora mi dà questo messaggio #122 ,anche se non è un problema però volevo capire a che è dovuto

**Comment by aantetomaso** [comment]
Probabilmente è qualche comando nel javascript della pagina caricata, che non viene correttamente interpretato, facciamo una verifica. Quanto alla gestione degli aggiornamenti, il problema dovrebbe essere stato sanato. 
Nessun problema su Windows 11.
