### ISSUE TITLE
certificato scaduto?

### ISSUE THREAD

**Issue by marzialerosi** [italia/cie-middleware#122]
salve, mi chiamo marzio, aiuto per favore

quando utilizzo l'app mi appare in continuazione questo messaggio in allegato, dice che il certificato è scaduto, di che certificato parla? come si risolve?

**STEP PER RIPRODURRE L'ERRORE**

- aprire cie middleware
- cliccare su informazioni (o aiuto) - si aprirà una finestra "errore nello script"
- cliccare sulla x per chiudere il pop-up e apparirà l'errore di certificato scaduto

**APP E OS**

```
App versione 1.4.3-4
Windows 11
```

grazie in anticipo

![24](https://user-images.githubusercontent.com/107806791/213944513-a537bf17-d099-484c-8ad4-cc88e8eac23a.png)
![25](https://user-images.githubusercontent.com/107806791/213944516-d8c8d91e-fb58-4261-8d80-275baccc6c15.png)

**Comment by aantetomaso** [comment]
Buongiorno, il certificato scaduto non è quello della sua carta, ma quello del Portale CIE, che è stato poi rinnovato.
