### ISSUE TITLE
impossibile da usare con la mia CIE....

### ISSUE THREAD

**Issue by p060477** [italia/cie-middleware#128]
Salve
non riesco ad usare la CIE ottengo sempre questo errore che vi allego quando tento di abbinare la carta
ho un lettore smart card NFC  iso 14443
questo:
https://www.trust.com/it/product/24736-ceto-contactless-smartcard-reader#faq
che è compatibile con i dati tecnici della CIE 3.0 in mio possesso

https://www.cartaidentita.interno.gov.it/downloads/2021/03/cie_3.0_-_specifiche_chip.pdf

ho un pc desktop windows 10 home 64
e il sw: CIE-Middleware-1.4.3-4  che eseguo con privilegi di amministratore.

ecco l'errore:
![Immagine](https://user-images.githubusercontent.com/12773559/227614968-739048b3-91a7-4353-84de-c1d095b22cc2.jpg)

e vi allego anche due log della applicazione in C:\%PROGRAMDATA%\CIEPKI 
sperando vi sia utile

cosa devo fare?

[CIEID_2023-03-24.log](https://github.com/italia/cie-middleware/files/11065633/CIEID_2023-03-24.log)
[CIEPKI_2023-03-24.log](https://github.com/italia/cie-middleware/files/11065634/CIEPKI_2023-03-24.log)

**Comment by AntonioCiccarelli** [comment]
Salve,
potreste cortesemente allegarci i log di Debug del software?
Per attivarli occorrerà andare in Impostazioni > Log > Modifica > Debug > Salva.

![image](https://github.com/italia/cie-middleware/assets/118728287/2b7f47f6-cae3-42a8-9e2a-b0e2af1f8a75)

Dopodiché sarà necessario ripetere l'operazione che genera l'errore ed allegarci i file che sono stati generati.

Grazie.

**Comment by p060477** [comment]
...questa ha veramente dell'incredibile...se non fosse vero sarebbe **tragi**comico...
Vi segnalo un problema il 24.03.2023, ripeto 2023, e rispondete dopo UN ANNO...??!
!...ma secondo voi un povero cittadino come avrebbe dovuto risolvere questo problema 
in questi DODICI mesi di vacatio nel Vostro farVi fattivamente attivi nel risolvere...??
...questa è veramente da segnalare a Report ....
...come siamo finiti ......
che infinita tristezza....

**Comment by AntonioCiccarelli** [comment]
Salve,
ci rendiamo conto che è trascorso molto tempo, ma purtroppo il progetto è su appalto e necessitiamo dell'autorizzazione da parte della Stazione Appaltante per poter procedere nella gestione delle segnalazioni.
Dal momento che vorremmo potervi ugualmente assistere e risolvere eventuali problematiche riscontrate, potreste gentilmente comunicarci se avete ancora bisogno di aiuto o se occorre procedere con la chiusura della issue?

Grazie.

**Comment by p060477** [comment]
di nuovo complimenti...aspettate 1 anno, -> 12 mesi...,->366 giorni...
e poi in un giorno chiudete...
se non fosse tragico...sarebbe veramente comico....
...come siamo finiti ......
**che infinita tristezza....**

**Comment by rnalrd** [comment]
Per quanto in ritardo, sarebbe più utile che lei postasse le informazioni richieste per aiutare altri concittadini affetti dallo stesso problema.

**Comment by p060477** [comment]
..e secondo voi **saremmo dovuti stare 1 anno ad aspettare questo vostro -tempestivo- interessamento**...??
...ci siamo dovuti arrangiare di volta in volta con la CNS o con lo SPID...
francamente al momento la voglia di rifarci il fegato grosso con la CIE non ci è ancora tornata
...e dovreste come **minimo** capirlo...

**Comment by p060477** [comment]
https://github.com/italia/cie-middleware/issues/169#issue-3778565040

**Comment by p060477** [comment]
> Salve, ci rendiamo conto che è trascorso molto tempo, però Github non è un canale di assistenza. Dal momento che vorremmo potervi ugualmente assistere e risolvere eventuali problematiche riscontrate, potreste gentilmente comunicarci se avete ancora bisogno di aiuto o se occorre procedere con la chiusura della issue?
> 
> Grazie.

se vorreste ancora rendervi utili...:
https://github.com/italia/cie-middleware/issues/169#issue-3778565040
