### ISSUE TITLE
LAMENTAZIONI DEI CITTADINI

### ISSUE THREAD

**Issue by raffaella30174** [italia/cie-middleware#129]
Buongiorno,
si stanno presentando diversi cittadini agli sportelli anagrafe (una quindicina in due giorni) lamentando il fatto che la loro CIE non funziona, non riescono ad accedere ai siti dell'INPS, AE  ecc.
Le abbiamo verificate nel portale : [verifica la ](https://www.cartaidentita.interno.gov.it/info-utili/servizio-di-verifica/) che restituisce il seguente messaggio: 
La Sua Carta di Identità Elettronica (CIE) avente seriale ........ non presenta difetti.
Abbiamo invitato i cittadini a chiamare il numero a loro dedicato di IPZ, ma ritornano dicendo che il Call Center dice loro di **richiedere l'emissione di una nuova  CIE in ESENZIONE**.
Chiediamo di sapere se ci sono notizie in merito a una serie di CIE difettose, perché così sembra di capire dalle risposte fornite dal Call Center di IPZ.
Cordiali saluti

**Comment by aantetomaso** [comment]
Purtroppo la segnalazione è troppo generica. Non siamo a conoscenza di CIE difettose, l'anomalia lamentata potrebbe dipendere da diversi fattori (non corretta configurazione del Software CIE, lettore acquistato, antenna del chip RF che si è guastata). Verifica CIE si riferisce solo ad una partita del 2018 dichiarata difettosa. Non ce ne sono state altre.
