### ISSUE TITLE
<ApplicationOverride> su Shibboleth: applicazione/risorsa già mappata per SPID

### ISSUE THREAD

**Issue by Eduardo1977** [italia/cie-middleware#130]
Buongiorno @aantetomaso,
per un’applicazione web che fornisce servizi ad un Ente pubblico dovrei attivare il servizio di autenticazione “Entra con CIE” mentre “Entra con SPID” c’è già da tempo.
Tecnicamente, l’accesso con SPID è stato realizzato su SP Shibboleth con protocollo SAML 2.
Per l’accesso con CIE dovrei utilizzare la stessa infrastruttura Shibboleth. Però, sto avendo qualche problema a trovare una configurazione in modo da farli coesistere senza apportare modifiche alla configurazione già fatta per SPID (per evitare di modificare il metadata già in uso).
Ho esposto il problema e la procedura adottata in maniera dettagliata su Forum Italia:
[https://forum.italia.it/t/applicationoverride-su-shibboleth-applicazione-risorsa-gia-mappata-per-spid/34602](https://forum.italia.it/t/applicationoverride-su-shibboleth-applicazione-risorsa-gia-mappata-per-spid/34602)

Ringrazio in anticipo per il supporto

Ing. Eduardo Gira
Tel. 0832 1522264
Servizi Locali Spa

Cordiali saluti

**Comment by aantetomaso** [comment]
Non è questo il repository di riferimento, suggerisco di riportare il quesito sui canali Slack di Developers Italia
