### ISSUE TITLE
Numero documento e data emissione?

### ISSUE THREAD

**Issue by aster94** [italia/cie-middleware#134]
Salve,

Stiamo sviluppando un applicazione per uno studio medico. Ci servirebbe leggere dalla CIE dei pazienti il numero del documento e la data di emissione. É possibile ottenerle in qualche modo?

**Comment by aantetomaso** [comment]
Salve, non è possibile farlo mediante il Software CIE ma mediante le SDK MRTD disponibili su Developers Italia.
https://github.com/italia/cie-mrtd-dotnet-sdk
https://github.com/italia/cie-mrtd-example-app

**Comment by aster94** [comment]
Grazie, si possono ottenere senza PIN o c'è bisogno che i pazienti li inseriscano?
