### ISSUE TITLE
Eccezione in fase di firma grafica PDF

### ISSUE THREAD

**Issue by AntonioCiccarelli** [italia/cie-middleware#135]
Risolvere il problema che causa il crash dell'applicativo, a causa della mancanza del bitmap di firma.

![Immagine](https://github.com/italia/cie-middleware/assets/118728287/3f10aa4d-378e-45d0-913f-dc28bb72cf3f)

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.8
