### ISSUE TITLE
Firma Grafica non funzionante

### ISSUE THREAD

**Issue by tamamma** [italia/cie-middleware#136]
Ci sono problemi con la firma grafica, quella custom attraverso il caricamento di un PNG.
Il PNG in questione ha il canale alfa come suggerito.
Quando viene generata la firma con il middleware CIE-ID (OSX Ventura) esce un blocco nero, sia se apro il PDF firmato con Adobe che con Anteprima.

Inoltre come enanchment sarebbe utile portare il focus del mouse direttamente sui campi in cui inserire il PIN quando ci si trova in tale step per apporre la firma digitale.

**Comment by aantetomaso** [comment]
Ciao e grazie mille del riscontro. 
Il problema è sotto Windows o sotto OSX? Se sotto OSX, cortesemente puoi aprire la issue nel repository di riferimento?
https://github.com/italia/cie-middleware-macos

**Comment by tamamma** [comment]
HO aperto la issue nel repository OSX come suggerito ma dal 6 marzo ad oggi ancora nessuno l'ha preso in carico...
