### ISSUE TITLE
SIGSEGV su Debian con OpenJDK 11

### ISSUE THREAD

**Issue by rdicosmo** [italia/cie-middleware#142]
Buongiorno,
    grazie per aver reso disponibile una versione dell'applicazione CIE per Linux.
Ho scaricato il pacchetto Debian, versione 1.4.3.5 disponibilie su https://www.cartaidentita.interno.gov.it/pa-e-imprese/documentazione-middleware-cie/ e lanciato l'applicazione.
Purtroppo, al momento dell'abbinamento della carta, l'applicazione esce con un SIGSEV giusto dopo aver introdotto il codice PIN.
Qui allegati:

- log dell'applicazione (lanciata a mano per ottenere il log) [hs_err_pid450364.log](https://github.com/italia/cie-middleware/files/13259226/hs_err_pid450364.log)
- segmento di dmesg che mostra il lettore NFC
[dmesg.log](https://github.com/italia/cie-middleware/files/13259238/dmesg.log)

Vi sarei grato se poteste indicarmi come sbloccare la situazione.

Grazie per il vostro lavoro.

**Comment by aantetomaso** [comment]
Salve, il repo di riferimento per Linux è https://github.com/italia/cie-middleware-linux.
La prego di voler riportare lì questa issue.
