### ISSUE TITLE
Errore in fase di accesso

### ISSUE THREAD

**Issue by barbax7** [italia/cie-middleware#145]
OS: Windows 10 64bit
CIE Software: 1.4.3.7
CIE: rilasciata a 11/2022
Firefox: 124.0.1
Chrome: 123.0.6312.86
Card reader: Trust CETO 

Sto avendo difficoltà a utilizzare l'accesso con CIE da desktop.
Ho installato il software middleware e abilitato la mia CIE nell'app, inserendo il pin. Ho successivamente riavviato il dispositivo e seguito il tutorial per aggiungere la libreria dll a Firefox. Se non avessi riavviato il pc, mi dava errore "impossibile aprire il file". Effettuato il riavvio, ho potuto caricare la dll, e spunta in questo modo:
![dll](https://github.com/italia/cie-middleware/assets/66796758/817cce64-296f-43c6-879d-dacbd3a51480)

Quando vado a fare accesso con CIE, una volta appoggiata la carta sul lettore e premuto "prosegui da pc", mi spunta la seguente schermata di errore, senza che mi fa scegliere né certificati né mi richieda pin:
![errore](https://github.com/italia/cie-middleware/assets/66796758/bda61693-fe29-4b01-b748-5c9d129d1891)

Stessa schermata di errore si presenta su Chrome, e andando a controllare i certificati installati, non spunta quello relativo alla mia CIE, come invece dovrebbe essere poiché tutta la configurazione è stata già impostata su un altro dispositivo con windows 11 e stessa versione di CIE Middleware (in questo secondo dispositivo, non capisco perché ma per ogni CIE spuntano due certificati, e uno dei due va in errore dicendo che è stato revocato. Inoltre c'è un problema di cache in quanto se accedo con una CIE in un sito, faccio logout, cambio CIE e riaccedo, il browser (o il cie middleware, non saprei) anziché leggere la nuova card, considera la precedente lettura e senza chiedere né certificato né pin accede all'utenza precedente).
La CIE funziona correttamente, perché utilizzata in questo secondo laptop e anche più volte da mobile con app CieID e CieSign

Segnalo anche, appena provato, che la firma dei documenti in pdf con e senza firma grafica va in stallo e non prosegue.

**Comment by barbax7** [comment]
Oggi qualcosa è cambiato. Ho tolto e riaggiunto la cie dal software, e faceva un po' di capricci perché andava sempre in errore durante la lettura. Ho aggiunto anche una seconda carta.
Da Chrome sono riuscito ad accedere, presentando comunque il problema dei due certificati e della cache.

Successivamene sono riuscito ad accedere anche da Firefox, che finalmente mi ha chiesto che certificato inviare e il pin. La finestra è fraintendibile perché chiede "la password per il token PKCS#11 CIE":
![pin](https://github.com/italia/cie-middleware/assets/66796758/e3db5fcc-3db9-4d6d-b264-1e68f83b637b)

In ogni caso, dopo l'inserimento del pin, va spesso in errore con la schermata al commento precedente. Poche volte, sui tanti tentativi, sono riuscito ad accedere, usando entrambe le CIE.
Dopo l'accesso, rimane il problema della cache che anche cambiando carta accede nuovamente all'utenza precedente perché (ho capito da firefox) viene inviato al sito il certificato letto dalla precedente lettura e memorizzato in cache.

Riguardo alla firma, su un terzo dispositivo con windows 10, la firma ha funzionato subito senza problemi. Sul mio dispositivo, usando due CIE diverse va in stallo.

**Comment by aantetomaso** [comment]
Può cortesemente aggiornare alla 1.4.3.9 e riprovare?

**Comment by barbax7** [comment]
Buongiorno Antonio, grazie per la risposta.
Nei giorni passati avevo ripreso a fare dei test e sembra che il problema principale fosse come Firefox gestisse il lettore modello Trust.
Inoltre avevo intenzione di aprire un topic su forum Italia per discutere sul funzionamento dei cookie di acesso.

Tornando agli argomenti della issue, ho scaricato la nuova versione, e sono riuscito a firmare un documento senza problemi.
Anche su Firefox il login ha funzionato.
Sembra che Firefox non riconosca il dispositivo di lettura qualora questo venga collegato mentre il browser è già aperto.
![immagine](https://github.com/user-attachments/assets/5890db09-34c1-406f-b820-f9c2d1431612)

Invece, aprendo il browser con il lettore già collegato, questo riconosce la presenza del lettore e indica che non c'è alcun dispositivo presente, riferendosi al supporto fisico del certificato, ossia la CIE
![immagine](https://github.com/user-attachments/assets/de60e9ab-daa0-41ad-851a-28c40b893a56)

Ho provato a fare il login a un sito della PA, e come immaginavo la prima volta (con lettore non riconosciuto) non mi ha chiesto né PIN nè certificato, e subito è andato in errore "No_client_certificate"
Riavviando il browser, e riconoscendo questa volta il lettore, il login ha funzionato come dovrebbe, ossia ha richiesto il PIN per leggere la CIE e ha chiesto quale certificato trasmettere per accede al sito web.


Mi sono reso conto che tali accessi generano dei cookie di sessione. Quindi quando io faccio il logout dal sito della PA, se voglio riaccedervi all'interno della stessa sessione tramite CIE livello 3, quando arrivo alla schermata "Prosegui con computer", posso cliccarci anche senza avere la CIE sul lettore, e il sito `idservice.servizicie.interno.gov.it` accede alla mia utenza, senza chiedere né PIN e né certificato, chiedendomi poi se voglio trasmettere le mie info personali al sito della PA per cui sto accedendo.
Questo comportamento, che immagino sfrutti i cookie di sessione, è il comportamento desiderato? Per chi deve accedere alla stessa PA con utenze diverse, a turno, è costretto a chiudere tutte le finestre del browser e riaprire. Inoltre, mantenendo la sessione aperta, chiunque può accedere ai siti della PA con la mia utenza senza che abbia fisicamente la mia CIE.
Andando infatti in gestione certificati, nelle impostazioni di Firefox, posso notare che il certificato di autenticazione è presente anche senza che la mia CIE sia nel lettore
![immagine](https://github.com/user-attachments/assets/4435b529-50c9-42ed-9ec1-5d7548116b5f)
