### ISSUE TITLE
Lo stato dell'applicazione riportato da 'Pannello di controllo'->'Programmi e funzionalità' lascia intendere sia possibile fare modifiche mentre invece si può solo disinstallare, ecco come ovviare

### ISSUE THREAD

**Issue by SwimmeRM** [italia/cie-middleware#149]
Lo stato dell'applicazione riportato da 'Pannello di controllo'->'Programmi e funzionalità' lascia intendere sia possibile fare modifiche mentre invece l'applicazione si può solo disinstallare.
Vedere la prima immagine allegata.
![CIE_Middleware_v1 4 3 8_install_date_now_properly_updated_but_application_status_seems_modificable_while_uninstall_is_only_allowed version_not_reported_by_ControlPanel_#0](https://github.com/italia/cie-middleware/assets/102351974/be759bc4-f1c6-48fa-a9de-a6206051c10a)
N.B. La soluzione comunque è molto semplice. Basta far aggiungere dal Setup un valore 'NoModify' REG_DWORD impostato a 0x1 per riuscire poi a vedere subito che l'applicazione è solo disinstallabile. In caso di necessità tale valore è comunque aggiungibile nel registry anche prima del rilascio di una nuova versione di CIE Middleware eseguendo il seguente comando da un prompt comandi con diritti amministrativi :
-  reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CIEPKI /v NoModify /t REG_DWORD /d 0x1

Ed ecco la seconda immagine allegata che mostra quale sarà il risultato finale.
![CIE_Middleware_v1 4 3 8_application_status_will_no_more_seems_modificable_with_proper_registry_entry_#1](https://github.com/italia/cie-middleware/assets/102351974/1e7f7c19-cfa3-47d3-9a79-3c0e02de34d1)

P.S. Il SO coinvolto è Windows 7 SP1 x64 Ultimate.
Grazie per l'attenzione.
Cordiali Saluti
Roberto

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.9
