### ISSUE TITLE
Neanche con l'installazione dell'ultima v1.4.3.8 il n° di versione dell'applicativo viene correttamente inserito nel registry, ecco però come ovviare

### ISSUE THREAD

**Issue by SwimmeRM** [italia/cie-middleware#150]
Neanche con l'installazione dell'ultima v1.4.3.8 il n° di versione dell'applicativo viene correttamente inserito nel registry. Lo stesso dicasi per la data d'installazione che non viene inserita nel registry, anche se comunque almeno ora con la v1.4.3.8 l'informazione riesce ad aggiornarsi correttamente (fino alla precedente v1.4.3.7 l'installazione come aggiornamento sulla precedente v1.4.1.0 ha lasciato inalterato il valore della data d'installazione risultante sempre da 'Pannello di controllo'->'Programmi e funzionalità', cioè quello della precedente v1.4.1.0 ossia 24/09/21).
Con l'installazione dell'ultima v1.4.3.8 vengono comunque inseriti, forse anche automaticamente e non volontarriamente, nel registry i seguenti valori (coi rispettivi contenuti): VersionMajor (=0) e VersionMinor (=1) entrambi REG_SZ che però non è detto siano quelli da usare realmente.
Anche in qs. caso, volendo è possibile risolvere la situazione anche prima del rilascio di una nuova versione di CIE Middleware eseguendo il seguente comando da un prompt comandi con diritti amministrativi :
- reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CIEPKI /v DisplayVersion /t REG_SZ /d "1.4.3.8"

Ed ecco quale sarà poi la visualizzazione risultante (N.B. anche senza rimuovere VersionMajor e VersionMinor)
![CIE_Middleware_v1 4 3 8_application_status_with_version_properly_added_into_expected_registry_entry_#2](https://github.com/italia/cie-middleware/assets/102351974/2aab77b0-a965-45ae-b76c-e84d94f20ecb)

Ecco poi i comandi supplementari per rimuovere VersionMajor e VersionMinor :
- reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CIEPKI /v VersionMajor /f
- reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CIEPKI /v VersionMinor /f

P.S. Il SO coinvolto è sempre Windows 7 SP1 x64 Ultimate.
Grazie per l'attenzione.
Cordiali Saluti
Roberto

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.9
