### ISSUE TITLE
Se con l'ultima versione CIEPKI.DLL (64bit) poi diventa v1.4.3.8, è corretto che la versione a 32bit in %SystemRoot%\SysWOW64 resti sempre la v1.3.0.6 ?

### ISSUE THREAD

**Issue by SwimmeRM** [italia/cie-middleware#152]
Se con l'ultima versione v1.4.3.8 anche CIEPKI.DLL (64bit) poi deve diventare v1.4.3.8 in %SystemRoot%\System32 (e dopo il previsto riavvio), è corretto che la versione a 32bit in %SystemRoot%\SysWOW64 debba ancora restare la stessa v1.3.0.6, che era stata inizialmente installata da CIE Middleware v1.4.1.0 e che neanche dopo aver installato la precedente versione v1.4.3.7 era poi stata riaggiornata ?

N.B. Domanda relativa a SO Windows 7 SP1 x64 Ultimate.

**Comment by aantetomaso** [comment]
è corretto, dalla 1.3.0.6 il Software CIE è solo a 64 bit. La 1.3.0.6 è l'ultima versione a 32 bit disponibile.
