### ISSUE TITLE
C:\Windows\System32\rundll32.exe CIEPKI.dll Update Display (2)

### ISSUE THREAD

**Issue by patch-work** [italia/cie-middleware#157]
Ri-apertura del ticket, perche' la soluzione proposta non funziona.

Ticket originale
https://github.com/italia/cie-middleware/issues/153

In aggiunta al ticket originale, l'applicativo non riconosce la CIE, chiede di abbinarla nuovamente, ma l'operazione fallisce.

Nuova evidenza del problema in allegato.

![IMG_20240724_093403_660](https://github.com/user-attachments/assets/51196f13-1020-4661-b420-a93b50f0f1a9)

**Comment by FVA-Bit4ID** [comment]
Salve,
Per supportarla abbiamo bisogno di alcune informazioni:
- Naviga tramite proxy?
- Si trova su una rete privata o pubblica?
- sono presenti sulla sua macchia degli antivirus con protezione web attiva?

Inoltre le chiediamo se gentilmente può inviarci i log di CIE ID relativi all'errore ed inoltre lo output del comando
"certutil -scinfo" lanciato da finestra di comando windows.

Saluti

**Comment by patch-work** [comment]
Ha ripreso a funzionare dopo l'ultimo aggiornamento di Windows.
