### ISSUE TITLE
Utilizzo del code signing per l'installer

### ISSUE THREAD

**Issue by rasky** [italia/cie-middleware#25]
L'installer MSI ufficiale dovrebbe essere firmato con un certificato valido di code-signing, al momento in cui faremo il primo rilascio ufficiale, per facilitare l'installazione su sistemi Windows in cui le policy di sicurezza non consentono l'installazione di software non firmato.

**Comment by fottavi** [comment]
Al momento l’installer è firmato con un certificato di Code Signing rilasciato a nome del Poligrafico da Actalis Authentication Root CA

Fabio

Da: Giovanni Bajo [mailto:notifications@github.com]
Inviato: venerdì 29 settembre 2017 12:55
A: italia/cie-middleware <cie-middleware@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [italia/cie-middleware] Utilizzo del code signing per l'installer (#25)


L'installer MSI ufficiale dovrebbe essere firmato con un certificato valido di code-signing, al momento in cui faremo il primo rilascio ufficiale, per facilitare l'installazione su sistemi Windows in cui le policy di sicurezza non consentono l'installazione di software non firmato.
