### ISSUE TITLE
Windows installation package - unneeded dependencies

### ISSUE THREAD

**Issue by gvarisco** [italia/cie-middleware#26]
https://github.com/italia/cie-middleware/tree/master/Setup currently relies on Javascript and ActiveX objects for performing all the available installer options (install, uninstall).

We should be probably looking at removing those unneeded dependencies by evaluating/adopting different frameworks:

- Best in my opinion would be to use Nullsoft Scriptable Install System (NSIS), a script-driven installer authoring tool for Microsoft Windows. Starting with v2.x, it supports LZMA compression, multiple languages, and an easy-to-use plugin system.
- WIX
- a combination of WIX and NSIS for wrapping MSI executables
- InstallShield

**Comment by gvarisco** [comment]
Additional projects mentioned on social networks:

- https://github.com/Squirrel/Squirrel.Windows (uses NuGet packages to create installation and update packages)

**Comment by madduci** [comment]
I would suggest WIX for building MSI installers which support upgrades based on a fixed GUID.
In addition, a whole project optimization based on CMake/Conan.io would improve the management of dependencies and the project build automatization including the above quoted installer generation (CMake can generate WIX installers).

Proposal: join the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to add some tickets/issues related to the above things.

**Comment by fottavi** [comment]
In the last PR #49 NSIS was used as setup engine.
It's simple and powerful, so it seemed the best option to me.
The installer compiled with NSIS will be available shortly

**Comment by hackbunny** [comment]
MSI packages are pretty much a requirement for deployment in enterprise environments. If we don't want to depend on Visual Studio's installer project add-on, a free and open source alternative to build a MSI installer is [WiX](http://wixtoolset.org/). WiX comes with its own Visual Studio add-on, and is now in fact recommended by Microsoft themselves to write Windows installers

Downside is that WiX isn't easy to use, and MSI itself has a pretty steep learning curve. But WiX is certainly the more "future-proof" choice
