### ISSUE TITLE
Buffer security checks are disabled for Release builds of CIEPKI.dll

### ISSUE THREAD

**Issue by hackbunny** [italia/cie-middleware#34]
For no good reason, Release builds of CIEPKI.dll are compiled with `/GS-`, disabling a basic and extremely important security mitigation. I have opened pull request #33 with a fix

**Comment by gvarisco** [comment]
Thanks @hackbunny for your contribution. @fottavi, I've assigned PR #33  to you. Once approved, I'm gonna merge it. +1 from my side.

**Comment by alexrj** [comment]
PR was merged, I'm closing this issue.
