### ISSUE TITLE
Develop demo application for reading and displaying card contents

### ISSUE THREAD

**Issue by alexrj** [italia/cie-middleware#37]
In order to facilitate developers to understand how to use this middleware, it would be useful to provide them with the source code of a full desktop application that reads the card DGs and displays data and photo.

An example scenario for such an app would be a hotel check-in, where people could just provide their CIE to the receptionist instead of having their paper ID photocopied. The app would even provide a quick way for sending data to the Police (which collects information about guests) through a web service.

**Comment by fottavi** [comment]
DGs can be read with ICAO SDK, not the middleware. There's a sample app in https://github.com/italia/cie-mrtd-sdk/tree/master/Test that could be a start point

**Comment by alexrj** [comment]
Oh right, I moved this issue to that repository at https://github.com/italia/cie-mrtd-sdk/issues/4
Closing this one.
