### ISSUE TITLE
Usare la funzione "Release" di GitHub per i rilasci

### ISSUE THREAD

**Issue by alexrj** [italia/cie-middleware#53]
Al momento i rilasci binari sono pubblicati all'interno del repository, nella directory `Setup/Release/`.
Per maggiore praticità andrebbero invece pubblicati attraverso la funzione [Releases](https://github.com/italia/cie-middleware/releases) di GitHub, che è fatta apposta. In questo modo nel repository teniamo solo il codice sorgente e non confondiamo gli utenti. Inoltre il clone risulta più leggero.

**Comment by alexrj** [comment]
Fatto, forse era effettivamente un problema di firewall. Ho rinominato il file in `CIE-Middleware-v0.1beta.exe` per includere la versione e ho inserito qualche riga di change log. L'ho lasciato in draft per consentirti di rivederlo e pubblicarlo.

**Comment by fottavi** [comment]
Pubblicato. Grazie @alexrj !
A questo punto direi che possiamo rimuovere la cartella Setup\Release
