### ISSUE TITLE
Porting manuale utente su ReadTheDocs/Docs Italia

### ISSUE THREAD

**Issue by alranel** [italia/cie-middleware#55]
Il manuale utente è al momento disponibile nei formati DOCX e PDF. La consultazione in questi formati è un po' faticosa, perché sono lunghi a causa dei molti screenshot (ad esempio le istruzioni per Firefox sono molto lunghe e possono confondere/spaventare gli utenti non interessati a Firefox).

Come per tutti i documenti tecnici di Developers Italia dobbiamo portare questo manuale su Docs Italia/ReadTheDocs per consentire la consultazione via web, con un menu di navigazione.

**Comment by AndreaTironi1** [comment]
Quindi Idea farebbe da middleware come fa il middleware della cie ma per smartphone, ovvero è "abilitante" a poter leggere il certificato e quindi firmare? O andrebbe fatta un'app di firma che parla direttamente con la CIE? Grazie, bello sentirti @valeriopaolini

**Comment by valeriopaolini** [comment]
Mi sembra che siano possibili entrambi gli scenari, ma non vorrei aver frainteso cosa intendi :)

**Comment by AndreaTironi1** [comment]
Domanda1: perchè posso usarla solo tra PA, è un tema tecnologico o legale?

**Comment by deligios** [comment]
@AndreaTironi1 Risposta1: è un tema tecnologico e legale.

1. Utilizzare un certificato di autenticazione per la sottoscrizione presenta un problema di sicurezza che malintenzionati potrebbero sfruttare per farti sottoscrivere documenti a tua insaputa.
2. Come giustamente evidenzia @valeriopaolini L'art. 61 del DPCM 22-02-2013 prevede che
> L’utilizzo della Carta d’Identità Elettronica, della Carta Nazionale dei Servizi, del documento d’identità dei pubblici dipendenti (Mod. ATe) , del passaporto elettronico e degli altri strumenti ad essi conformi sostituisce, nei confronti della pubblica amministrazione,la firma elettronica avanzata ai sensi delle presenti regole tecniche per i servizi e le attività di cui agli articoli 64 e 65 del codice.

Penso che il legislatore abbia fatto questa scelta perché è improbabile che la PA voglia farti sottoscrivere documenti a tua insaputa...  ;)

**Comment by ugochirico** [comment]
L'art-61 del del DPCM 22-02-2013, per come è stato scritto, ha comunque in sé un errore: a differenza della CIE e della CNS che hanno almeno una chiave/certificato di autenticazione, il passaporto elettronico non ha al suo interno alcuna chiave crittografica disponibile per l'utente e, pertanto, non può in alcun modo essere usato come strumento di firma digitale.
