### ISSUE TITLE
Documentazione per sviluppatori

### ISSUE THREAD

**Issue by alranel** [italia/cie-middleware#56]
Bisogna scrivere una guida (su Docs Italia/ReadTheDocs) sulle API offerte dal middleware agli sviluppatori: cosa ci si può fare, quali dati si possono leggere, come si gestiscono gli errori eccetera.

**Comment by alexrj** [comment]
Serve anche documentazione su come configurare un web server per consentire l'autenticazione con CIE (quindi l'aspetto complementare del middleware), incluse le best practice per validare le CRL o usare OCSD (di cui trovo menzione solo [nel forum](https://forum.italia.it/t/certificate-revocation-list-cie/1639/2)) e anche per supportare correttamente il login sia con SPID sia con CIE.

**Comment by aantetomaso** [comment]
Chiudo perchè duplicata dalla issue #110
