### ISSUE TITLE
Aggiungere la possibilità di dare il permesso fotocamera

### ISSUE THREAD

**Issue by AndreaTironi1** [italia/cie-middleware#71]
Dopo aver installato l'app, se voglio fare una scansione della CIE, l'app va in crash fino a che manualmente non le dò il permesso di accesso alla fotocamera. Visto che non tutti sono in grado di capire questo e poi attivare l'accesso alla fotocamera, propongo di mettere la richiesta di default in installazione oppure di mettere un popup che chieda l'accesso alla fotocamera nel momento in cui uno vuole fare la scansione.

Altrimenti la user experience è terribile, ovvero l'app va in crash e si riavvia ogni volta.

**Comment by ebrienza** [comment]
Buongiorno @AndreaTironi1, questo è la repository per il progetto Cie-middleware. 
Se non erro la issue riportata fa riferimento ad un'app Android, probabilmente l'app iDea. Corretto? 
Se così fosse conviene spostare la conversazione altrove. Raccogliamo comunque la segnalazione.

**Comment by AndreaTironi1** [comment]
grazie si, devo aver cliccato sul link sbagliato in partenza e poi ho
inserito le isse al volo senza guardarle
le sposta gentilmente lei tutte e 3?

grazie

Il giorno mer 9 ott 2019 alle ore 08:59 Eros Brienza <
notifications@github.com> ha scritto:

**Comment by AndreaTironi1** [comment]
Errore di inserimento
