### ISSUE TITLE
Abbinamento e gestione di più di una CIE

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware#77]
La versione attuale del Software CIE consente l'abbinamento di al più una CIE.
E' necessario prevedere la gestione di più carte sul medesimo terminale/sulla medesima postazione.

**Comment by GabryJ84** [comment]
E' una cosa OBBLIGATORIA direi...in casa siamo in 4 e la CNS la possono tranquillamente usare tutte e 4 le persone semplicemente inserendo e disinserendo alla bisogna.
Se non è possibile usare tutte e 4 le CIE sul lettore è una cosa assolutamente inutile.

**Comment by aantetomaso** [comment]
Grazie del commento. Questo sviluppo verrà affrontato a partire dal mese di settembre, contiamo di uscire entro la fine dell'anno.

**Comment by aantetomaso** [comment]
Risolta nella versione 1.3.2.0
