### ISSUE TITLE
EsempioPKCS11.cpp non funziona...

### ISSUE THREAD

**Issue by mistermongi** [italia/cie-middleware#80]
Salve,
l'esempio CPP presente non sembra funzionare.
Se eseguito fallisce sistematicamente la C_OpensSession con:
**result = E1 (token not recognized)**

I lettore utilizzato è specifico per CIE; fornitore bit4id.

Noto che nella CIEPKI.dll ci sono 4 funzioni in più delle solite pkcs11: vengono chiamate dal programma in c# (che invece funziona correttamente) e fanno uno scambio di chiavi diffie-hellman.

E' possibile per favore avere qualche indicazione?
Grazie

**Comment by arg7** [comment]
Ho avuto lo stesso problema, pero ho notato che se faccio build a 64bit del EsempioPKCS11.cpp allora funziona.
Strano.

**Comment by aantetomaso** [comment]
Il Software CIE è a 64 bit. Occorre compilare a 64 bit.
