### ISSUE TITLE
Carta emessa 20 Agosto + CIE Middleware 1.3.0.8 = CRASH

### ISSUE THREAD

**Issue by GabryJ84** [italia/cie-middleware#81]
Come da titolo...CIE emessa il 20 di Agosto manda in crash il programma tutte le volte, una volta che arriva alla lettura dei certificati.

**Comment by aantetomaso** [comment]
Si consiglia di installare la 1.3.2.0. La versione 1.3.0.8 non era compatibile con le carte CIE 3.0 aderenti alle raccomandazioni ICAO V.7
