### ISSUE TITLE
Compatibilità con nuovi chip ST - 2021

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware#84]
Garantire la compatibilità del Software CIE con i nuovi chip ST, per i quali è prevista l'uscita in produzione entro l'estate.

**Comment by marcom1981** [comment]
Salve, sarebbe possibile anticipare gli ATR di questi dispositivi in modo da avvantaggiarci anche noi all'adeguamento ?

**Comment by aantetomaso** [comment]
Risolta nella 1.4.0.0
