### ISSUE TITLE
Abbinamento CIE non funziona

### ISSUE THREAD

**Issue by fiorins** [italia/cie-middleware#89]
Ho l'ultima versione del software 1.4 e quando provo ad abbinare la mia CIE mi esce errore inaspettato della SmartCard mentre un'altra CIE in famiglia non ha problemi, fa cosi anche sull'ultimo middleware di macOS
![20210428_152721](https://user-images.githubusercontent.com/32281481/116415463-bba9c600-a839-11eb-8d43-24b4dc3ff8ec.jpg)

**Comment by aantetomaso** [comment]
Probabilmente c'è qualche problema legato al chip della sua carta. Le suggerisco di effettuare un test di autenticazione con CIE ID da smartphone. Se anche in quel caso ha problemi dovrebbe rivolgersi al Comune e richiedere una riemissione.

**Comment by fiorins** [comment]
> Probabilmente c'è qualche problema legato al chip della sua carta. Le suggerisco di effettuare un test di autenticazione con CIE ID da smartphone. Se anche in quel caso ha problemi dovrebbe rivolgersi al Comune e richiedere una riemissione.

Sull'app CieID funziona tranquillamente e mi fa anche cambiare pin, presumo sia qualche errore del software

**Comment by aantetomaso** [comment]
@bitpdg @bit4gam possiamo verificare?

**Comment by fiorins** [comment]
Sull'app CieID funziona tranquillamente e mi fa anche cambiare pin, presumo sia qualche errore del software, ho provato a fare l'accesso al sito dell'AE e funziona benissimo

**Comment by fiorins** [comment]
Aggiungo che con una versione precedente del middleware l'abbinamento funziona

**Comment by aantetomaso** [comment]
quale è l'ultima versione funzionante?

**Comment by fiorins** [comment]
Né dal pannello di controllo e né dalla sezione Informazioni dell'app riesco a capire che versione è, comunque ecco una foto
![20210429_150838](https://user-images.githubusercontent.com/32281481/116555872-25d76f00-a8fd-11eb-91a8-93602f997f1d.jpg)

**Comment by aantetomaso** [comment]
Dalla data che leggo sembrerebbe quella immediatamente precedente. Posso chiederle una verifica scaricando ed installando prima questo pacchetto:

https://github.com/italia/cie-middleware/releases/tag/1.3.3.1

e, se non dovesse funzionare quest'altro?

https://github.com/italia/cie-middleware/releases/tag/1.3.3.0

Grazie della collaborazione.

**Comment by fiorins** [comment]
Tutte e due le versioni funzionano

**Comment by aantetomaso** [comment]
OK, quindi qualcosa non va con la 1.4.0 allora. Potrebbe cortesemente, carta sul lettore, aprire un prompt di DOS e lanciare il comando "certutil -scinfo > report.txt"?
Potrebbe poi inviare il file report.txt all'indirizzo a.antetomaso@ipzs.it?
La ringrazio.

**Comment by fiorins** [comment]
Ok, ho provato con tutte e due le versioni ma mi esce questo avviso:
![1 4](https://user-images.githubusercontent.com/32281481/116589801-50392480-a91d-11eb-84ab-96824ab6223c.jpg)

![1 3](https://user-images.githubusercontent.com/32281481/116589574-136d2d80-a91d-11eb-8a20-50009339d3fd.jpg)

Inoltre ho provato ad eliminare le carte che sono attualmente abilitate ma mi dice "Impossibile disabilitare la CIE", temo sia andato in tilt il software con tutte queste prove e cambi di versione.

**Comment by aantetomaso** [comment]
Provi ad eseguire questa procedura:

1) Disinstalli il software CIE
2) Elimini la cartella CIEPKI sotto C:\%ProgramData% utilizzando "Esplora Risorse"
3) Elimini la cartella IPZS sotto C:\%LOCALAPPADTA% utilizzando "Esplora Risorse"
4) Installi nuovamente il software, avvii CIE ID e chiuda il tutorial
5) Provi ad abbinare solo la sua CIE
6) Se fallisce l'abbinamento, ripeta il comando certutil -scinfo > report.txt da terminale e invii il file report.txt

**Comment by fiorins** [comment]
Ho disinstallato il software e sotto questi percorsi non c'erano queste cartelle, dopodiché ho reinstallato l'ultimo middleware ma ho ritrovate le carte abbinate e mi è impossibile disassociarle.

**Comment by massiemassie** [comment]
Ho sempre avuto anche io lo stesso problema di erroe inaspettato nella fase di abbinamento  (con tutte le verioni del middleware) per cui la uso con lo smartphone anche da pc. Non è che confligge con altri due lettori installati, uno con cns e firma ?
Gestione risorse smart card in esecuzione.
Stato corrente lettore/scheda:
Lettori: 3
  0: Bit4ID Key4 0 0
  1: Gemplus USB Smart Card Reader 0
  2: REINER SCT cyberJack RFID basis 1
--- Lettore: Bit4ID Key4 0 0
--- Stato: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
--- Stato: La scheda Þ condivisa da un processo.
---   Scheda:   Incard  JS2048
---    ATR:
	3b ff 18 00 00 81 31 fe  55 00 6b 02 09 04 03 01   ;.....1.U.k.....
	01 01 43 4e 53 10 31 80  65                        ..CNS.1.e

--- Lettore: Gemplus USB Smart Card Reader 0
--- Stato: SCARD_STATE_EMPTY
--- Stato: Nessuna scheda.
---   Scheda:
--- Lettore: REINER SCT cyberJack RFID basis 1
--- Stato: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Stato: La scheda Þ disponibile per l'utilizzo.
---   Scheda: CIE_2
---    ATR:
	3b 8f 80 01 80 31 80 65  b0 85 04 00 11 12 0f ff   ;....1.e........
	82 90 00 8a                                        ....

**Comment by mdesalvo** [comment]
Confermo la problematica con lettore **uTrust 3700F**: ho provato almeno le 3 più recenti versioni del middleware su sistema operativo Windows 10 20H2. Non c'è verso di superare la **fase di lettura del certificato**: fallisce sempre con l'errore "inaspettato". L'esecuzione del comando suggerito comporta la comparsa di una finestra di avviso con errore descritto.

Non è un problema della carta d'identità, infatti viene rilevata correttamente dagli strumenti di diagnostica di Identiv. 
E' un problema **grave** e frustrante di questo software.

**Comment by fedegiova** [comment]
Buongiorno, ho anche io il medesimo problema,

"Errore inaspettato durante la comunicazione"

Versione 1.4.1 su arch linux, c'e qualche informazione che vi posso mandare per diagnosticarlo meglio? Il software funziona correttamente con le carte rilasciate circa 2 anni fa ma con una appena emessa ( novembre 21) non si riesce a fare l'abbinamento.

.su terminale
```
^CInizio Sessione - versione: Apr 15 2021 06:30:48RESET CARDRisposta della smart card non validaRisposta della smart card non valida%  
```



.ciepki/ciepki.log
```
00000:[15:24:031]|13854|-1926962555|00|Applicazione chiamante:
Module 00: CIEPKC11
00001:[15:24:032]|13854|-1926962555|00|IN -> IAS
00002:[15:24:032]|13854|-1926962555|00| IN -> setTransmitCallback
00003:[15:24:032]|13854|-1926962555|00| OUT -> setTransmitCallback (2)
00004:[15:24:032]|13854|-1926962555|00|OUT -> IAS (1)
00005:[15:24:032]|13854|-1926962555|00|IN -> setTransmitCallbackData
00006:[15:24:032]|13854|-1926962555|00|OUT -> setTransmitCallbackData (5)
00007:[15:24:032]|13854|-1926962555|00|IN -> Reset
00008:[15:24:032]|13854|-1926962555|00| IN -> Transmit
00009:[15:24:032]|13854|-1926962555|00| OUT -> Transmit (8)
00010:[15:24:032]|13854|-1926962555|00|OUT -> Reset (7)
00011:[15:24:032]|13854|-1926962555|00|IN -> SelectAID_IAS
00012:[15:24:032]|13854|-1926962555|00| IN -> ReadCIEType
00013:[15:24:032]|13854|-1926962555|00| OUT -> ReadCIEType (12)
00014:[15:24:032]|13854|-1926962555|00| IN -> SendAPDU
00015:[15:24:032]|13854|-1926962555|00|  IN -> Transmit
00016:[15:24:032]|13854|-1926962555|00|  OUT -> Transmit (15)
00017:[15:24:032]|13854|-1926962555|00| OUT -> SendAPDU (14)
00018:[15:24:032]|13854|-1926962555|00|OUT -> SelectAID_IAS (11)
~                                                                  
```

**Comment by vipa7070** [comment]
Confermo di avere lo stesso problema riportato da @fedegiova e @fiorins sul mio sistema:

- sistema operativo: win 7 pro 32 bit;
- versione middleware: 1.4.3.1;
- lettore smart card: Bit4id miniLector AIR v3.

Non ho la possibilità di verificare se il problema possa essere dovuto alla mia CIE o al middleware perché né io né i miei conoscenti disponiamo di uno smartphone con interfaccia NFC. 
Ho anche provato versioni precedenti del middleware, ma con nessuna versione sono riuscito ad ottenere l'abbinamento.
Ho testato il lettore smart card con la tessera sanitaria/CNS e funziona; riesco ad accedere al sito INPS ed Agenzia delle Entrate, mentre con la CIE non funziona.
Quando poggio la CIE sul lettore inizia l'installazione del Driver che non va a buon file. Questo è quello che si ha:

![Cattura](https://user-images.githubusercontent.com/46306351/188719012-a3a7850f-2d61-4a42-b829-30b8eaa268f5.PNG)

Ovviamente lanciando l'applicazione CIE ID e provando a fare l'abbinamento si hanno problemi. Con l'ultima versione (1.4.3.1) il processo si blocca e l'applicazione resta come in questa immagine:

![Cattura5](https://user-images.githubusercontent.com/46306351/188719291-8790db55-259e-484f-b7e0-dab9e7638a22.PNG)

Con versioni precedenti ho ottenuto gli errori mostrati nelle seguenti immagini:

![Cattura2](https://user-images.githubusercontent.com/46306351/188719677-02e3b3e6-9cc0-4fcf-9734-ac7fc0949f6a.PNG)
![Cattura4](https://user-images.githubusercontent.com/46306351/188719875-768bcfe2-f5b9-4293-8cd7-68b58e008266.PNG)

Andando il "Gestioni Dispositivi" si osserva un problema con il driver della smart card:
![PD1](https://user-images.githubusercontent.com/46306351/188722719-d5743ac2-c10e-4102-aeb4-c4e0c4be9f38.PNG)

Non so se questo possa avere importanza, ma posso dire che con la tessera sanitaria/CNS non compare la voce "Altri dispositivi" e "Smart card" in "Gestione Dispositivi", mentre con la CIE sul lettore compare questa voce in "Gestione dispositivi".

Infine in una cartella ho trovato 3 file di log  generati da non so quale delle versioni che ho provato che provvederò ad inviare all'indirizzo di posta [a.antetomaso@ipzs.it](mailto:a.antetomaso@ipzs.it)

**Comment by aantetomaso** [comment]
Grazie, come suggerito in mail a vipa7070, occorrerebbe abilitare da CIEID, i log in modalità DEBUG, fare un tentativo di lettura ed inviare i files di log aggiornati presenti su c:\%PROGRAMDATA%\CIEPKI
Inviateli pure alla mia mail, grazie.

**Comment by vipa7070** [comment]
Ho eseguito alcune prove più approfondite con varie versioni del CIE-Middleware sul mio sistema che ha le seguenti caratteristiche:

- windows 7 pro 32bit
- lettore bit4id miniLector AIR v3
- carta d'identità elettronica (CIE) emessa il 13.05.2021

### Prova con la versione 1.4.3.1 del CIE-Middleware
Un primo problema che riscontro con questa versione è che l'installatore di questa versione del middleware non installa la libreria CIEPKI.dll nella cartella “Windows\System32”. Non sono un esperto in programmazione, ma guardando nei dettagli dell'installazione (vedi immagine sotto) si vede che l'installatore estrae, esegue e poi elimina un file denominato “vcredist_x64.exe” che è per un'architettura a 64 bit, mentre il mio sistema è a 32 bit. 

![Cattura](https://user-images.githubusercontent.com/46306351/189539928-45125738-b3f9-4b3b-8437-736f61be880c.PNG)

L'applicazione CIE ID comunque è presente e si avvia senza problemi. 
Poggiando la CIE sul lettore inizia l'installazione di un driver che non va a buon fine:

![immagine](https://user-images.githubusercontent.com/46306351/189540027-09bda927-b035-4518-9308-919cebc0296b.png)

![immagine](https://user-images.githubusercontent.com/46306351/189540042-6e7969e0-57ca-4abe-8cf8-c08427593085.png)

Continuando e provando a fare l'abbinamento inserendo il PIN, l'applicazione CIE ID resta come “congelata” nello stato mostrato nell'immagine sotto e non va oltre:

![immagine](https://user-images.githubusercontent.com/46306351/189540071-97a8b83c-cc74-4c61-863f-3a126e107622.png)

L'applicazione CIE ID mi lascia cambiare il PIN della mia CIE.
Impostando il log dell'applicazione e della libreria a livello “debug” si ottiene solo un file di log per l'applicazione (CIEID__data_.log) in quanto, come ho detto, la libreria non è stata installata. Qui sotto riporto quanto compare in un file di log dell'applicazione (CIE ID) in seguito ad un tentativo di abbinamento:

![immagine](https://user-images.githubusercontent.com/46306351/189540126-b31f8208-3c9d-4514-84af-e62163bb8cbe.png)

Colgo l'occasione per segnalare che ci deve essere qualche errore nella mascherina per introdurre il PIN in quanto questa mascherina lascia inserire anche 2 numeri nella stessa casella come mostrato in questa immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189540170-ae11f2e3-f7e1-41ff-8e8c-7a8114fee6bf.png)

### Prova con la versione 1.4.2.0
Con la versione 1.4.2.0 riscontro gli stessi problemi che ho avuto con la versione 1.4.3.1 ossia:

- non viene installata la libreria “CIEPKI.dll” nella cartella “Windows\System32”;
- quando si poggia la CIE sul lettore l'installazione del driver della smart card non va a buon fine;
- l'applicazione CIE ID è presente e parte, lascia cambiare il PIN della CIE, ma l'abbinamento non va a buon fine e l'applicazione resta come “congelata”.

Impostando il log a livello “debug” sia per l'applicazione che per la libreria (che non è però installata) e compiendo un tentativo di abbinamento si ottiene un file di log per la sola applicazione che contiene quanto riportato in quest'immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189540392-680d39e9-81f2-486e-846b-354327e4cd8a.png)

### Prova con la versione 1.4.1.0

La versione 1.4.1.0, a differenza delle versioni di cui ho parlato in precedenza, installa la libreria “CIEPKI.dll” nella cartella “Windows\System32”. Come si può vedere dalla seguente immagine questa libreria porta come “Ultima modifica” il 14/05/2020 17:02 e come “Dimensione” 1.341KB.

![immagine](https://user-images.githubusercontent.com/46306351/189540436-853a7096-14ff-4e32-922e-95f2955d5d29.png)

Guardando ai dettagli dell'installazione si vede che, per questa versione, non viene estratto, eseguito ed eliminato il file “vcredist_x64.exe”:

![immagine](https://user-images.githubusercontent.com/46306351/189540455-a676c65c-77aa-4e80-8738-571d3aad7965.png)

Comunque gli altri problemi permangono anche per questa versione:
- quando si poggia la CIE sul lettore l'installazione del driver della smart card non va a buon fine;
- l'applicazione CIE ID è presente e parte, lascia cambiare il PIN della CIE, ma l'abbinamento non va a buon fine. In questa versione l'applicazione non resta “congelata”, ma dà l'errore mostrato nella seguente immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189540611-8831fdae-a080-45fe-979c-fd0bf78f380f.png)

In questa versione non ho trovato il modo di impostare il log a livello “debug” in quanto nella sezione “Impostazioni” non è presente la scheda per poter fare questa impostazione. Nella cartella “ProgramData\CIEPKI” è comunque presente un file di log che provvederò ad inviare all'indirizzo di posta elettronica indicato in precedenza.
In questa versione del middleware nell'area delle notifiche (cosiddetto system tray) compare un'icona con la richiesta di “Premere per abilitare la CIE”. Questa è un'immagine che ho catturato alcuni giorni fa durante una prova:

![immagine](https://user-images.githubusercontent.com/46306351/189540674-98ced8ec-d72c-46d6-8c45-728a64ac1f01.png)

Cliccando sull'icona si avvia l'applicazione CIE ID ed immediatamente compare l'errore mostrato nella seguente immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189540695-1e3cb8ba-7d54-4d28-b243-40abc9f2e49b.png)

Cliccando su OK compare una segnalazione di crash dell'applicazione i cui dettagli si possono vedere in queste due immagini:

![immagine](https://user-images.githubusercontent.com/46306351/189540723-6e3d9ce7-71f2-4ff1-a2fb-233b683bfe19.png)

![immagine](https://user-images.githubusercontent.com/46306351/189540730-02810100-09f1-4e01-b56e-9491907c4384.png)

Come consigliato in un post precedente ho eseguito la seguente istruzione da riga di comando: certutil -scinfo > reportVer1410.txt
Facendolo con CIE sul lettore compare la finestra mostrata nella seguente immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189541091-32338aa9-66ca-4829-88f3-eab314309c67.png)

Premendo su dettagli si ottiene quanto mostrato nella seguente immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189541105-20483026-830e-47c4-861c-82cebd92cff5.png)

Cliccando su “Annulla” la finestra si ripresenta e così per un paio di volte e poi il comando termina producendo un report che provvederò ad inviare all'indirizzo di posta elettronica indicato precedentemente.

### Versione 1.4.3.1 senza disinstallare la versione 1.4.1.0

Installando la versione 1.4.3.1 senza prima disinstallare la versione 1.4.1.0 si ha che la libreria “CIEPKI.dll” rimane nella cartella “Windows\System32”. A questo punto è possibile fare un log a livello debug anche per questa versione della libreria in quanto ora è presente l'opportuna scheda nell'applicazione CIE ID. Provando a compiere un abbinamento ora, a differenza di prima, l'applicazione dà l'errore mostrato nella seguente immagine:

![immagine](https://user-images.githubusercontent.com/46306351/189541162-1d09dffa-8ed7-4143-be67-05cfcf83749b.png)

Provvederò ad inviare il file di log dell'applicazione e della libreria durante un tentativo di abbinamento all'indirizzo di posta elettronica indicata precedentemente.

**Comment by aantetomaso** [comment]
Grazie molte delle prove, del tempo speso e del feedback.

La versione 1.4 del Middleware tuttavia non è compatibile con i sistemi a 32 bit come giustamente segnalato. La mancata installazione della libreria CIEPKCS11 sotto system32 provoca proprio i fenomeni da lei osservati, essendo il cuore del middleware e di fatto il "driver" della CIE nel sistema operativo Windows.

Sicuramente può essere migliorata la gestione di 32/64 bit in termini di feedback (non ha senso far eseguire CIEID senza libreria) ma quanto osservato è in linea. Su sistemi a 32bit occorre utilizzare la versione 1.3. 

Grazie anche del feedback sulla finestra del PIN.

Non occorrono i log, quanto accade è chiaro.

Chiudo dunque questa segnalazione e apro due issues relative alla gestione migliorata di 32/64 bit e alla finestra del PIN.
Grazie.

**Comment by vipa7070** [comment]
Ho provato adesso, e neanche con la versione 1.3.3.0 non riesco a fare l'abbinamento e l'errore che si verifica è, come per le versioni 1.4, "Errore inaspettato durante la comunicazione con la smart card". Inoltre la libreria "CIEPKI.dll" in System32 pare essere esattamente la stessa stesse dimensioni e stessa data ore e minuti di ultima modifica.
