### ISSUE TITLE
Le nuove CIE non vengono lette dal middleware

### ISSUE THREAD

**Issue by deligios** [italia/cie-middleware#91]
Ho appena ricevuto una nuova CIE (quella precedente apparteneva a un lotto con errore di data nel certificato)
Appena appoggiata sul lettore NFC viene vista, ma dopo 5 secondi si disconnette.
Non è quindi possibile utilizzarla con CIE-ID

**Comment by aantetomaso** [comment]
Salve,
può dipendere dall'accoppiamento tra l'antenna e il lettore di smart card. Provi a creare una piccola distanza tra la base del lettore e la carta e ci dica come va. Basta anche poggiare la carta trasversalmente alla base del lettore o tenerla sollevata mezzo centimetro, di modo da creare un accoppiamento elettromagnetico migliore.

**Comment by deligios** [comment]
Il problema si manifestacomunque:
Appoggio la carta, viene vista, viene persa
https://user-images.githubusercontent.com/5829983/133798588-56d75b76-715a-4ade-9fed-6afeb889e21a.mp4

Con gli stessi lettori la carta precedente funzionava

**Comment by aantetomaso** [comment]
Non si riesce a vedere il filmato. Con il cellulare la carta funziona correttamente oppure anche in quel caso non va?

**Comment by deligios** [comment]
Non si tratta di un filmato, solo dei suoni emessi dal PC nell'intervallo carta-in carta-out
Persone affidabili mi hanno detto che è un problema noto dei nuovi microchip st risolto nel middleware android e forse non risolto nel middleware W10

**Comment by aantetomaso** [comment]
Non abbiamo evidenza di tali problemi con i chip ST attualmente utilizzati in produzione. Con alcuni modelli di lettore abbiamo sperimentato un fenomeno simile dovuto all'accoppiamento antenna-base del lettore. Il fenomeno, non imputabile al processore, nè al middleware (che non arriva ad un livello così basso di dialogo con la carta), poteva essere aggirato facilmente creando una piccola distanza tra la carta e il lettore stesso. Dai suoni tuttavia non so dire se il fenomeno è lo stesso, le informazioni sono troppo poche. Ad ogni modo, se la carta non opera correttamente, può richiedere una ristampa senza oneri al Comune.
