### ISSUE TITLE
Carta abbinata ma non riconosciuta in login

### ISSUE THREAD

**Issue by swim89** [italia/cie-middleware#92]
Ciao a tutti, sono riuscito ad abbinare correttamente la carta al middleware CIE ma nel momento in cui apro un sito che richiedere accesso con CIE ricevo la pagina  di seguito.

![Schermata 2021-06-25 alle 21 13 32](https://user-images.githubusercontent.com/2925880/123474468-49b3ea00-d5fa-11eb-80bd-46f42a87ad7b.png)

Il sito utilizzato per il login è il seguente: https://www.prenotazionicie.interno.gov.it/cittadino/n/sc/loginCittadino/sceltaLogin 
L'indirizzo che vedo nella barra in alto, nella pagina in cui visualizzo l'errore, è il seguente:
`https://idserver.servizicie.interno.gov.it/idp/errorcode.jsp?err=No_client_certificate&link=https://idserver.servizicie.interno.gov.it/idp/x509-prompt.jsp%3fconversation=e1s2`

Sistema operativo: Windows 10 Pro (Sistema operativo a 64 bit, processore basato su x64)
Browser: Google Chrome / Mozilla Firefox
Versione Middleware: v.1.4.1.0

**Comment by cvignati** [comment]
Hai provato a cancellare la caxhe del browser?
Che antivirus hai installato? Io ho avuto problemi con Kaspersky

**Comment by aantetomaso** [comment]
L'anomalia sussiste ancora?
