### ISSUE TITLE
ATR nuove carte identità

### ISSUE THREAD

**Issue by Kaizer69** [italia/cie-middleware#95]
Buona sera. I tanti errori che vengono segnalati "Errore inaspettato durante la lettura della smartcard" sono dovuto all'ATR non riconosciuto di alcune nuove carte d'identità.

Esempio di un (parziale) ATR non riconosciuto: **3b 8e 80 01 10 78 77 b1**

Va aggiunto in **StoreProvider.cpp** nella funzione:
`extern "C" HRESULT __stdcall DllRegisterServer(void)`

e probabilmente variato/aggiunto anche in **IAS.cpp** un nuovo ATR (es Gemalto_ATR)

**Comment by Kaizer69** [comment]
Aggiungo che potrebbe esserci qualcosa da variare in IAS.cpp

Es: Gemalto_ATR, ecc

**Comment by aantetomaso** [comment]
Aggiungere il supporto per il nuovo chip CIE Actalis

**Comment by aantetomaso** [comment]
Aggiungere compatibilità con chip Actalis e Bit4ID

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.1
