### ISSUE TITLE
Tre chiarimenti su cie

### ISSUE THREAD

**Issue by avagraha** [italia/cie-middleware#96]
Salve, qualche domanda se potete aiutarmi:

1) Qualche CIE 3 è analizzata da certutil come "CIE_3", mentre altre CIE 3
come "CIE_2" , pur rilasciate in agosto 2021 e che permettono tutti gli
accessi senza problemi. Come mai questa doppia denominazione del chip se gli
esiti sono fortunatamente identici? in pratica oggi ci sono tre tipologie di
chip per CIE3.0 ossia CIE_1, CIE_2, CIE_3 !?!

2) Il PIN della cie è custodito nel chip invisibile dentro la cie, giusto? e
su di esso si può scrivere mediante Middleware CIE, giusto? altrimenti non
si potrebbe cambiare il PIN. Ebbene curiosamente Voi qui su github (pagina
principale) affermate che è "ReadOnly".

3) Perché ciepki.dll lavora tanto in background? cosa caspita deve
cancellare tante volte al giorno, ogni santo giorno, anche se NON in uso, al
punto da riempirmi il disco con grossi log contenenti questi dati?

postimg.cc/xcHSRXQ2

Mi chiedo se sia normale tanto lavoro se non in uso.

Grazie.

**Comment by avagraha** [comment]
Queste pagine sono seguite o abbandonate?

**Comment by netdiver** [comment]
MI rispondo da solo:
%ProgramData%\CIEPKI

**Comment by avagraha** [comment]
Ciao, credo che basti aprire il browser (dove avevi caricato ciepki.dll) e 
partono i log infiniti, perché non trova il lettore USB. Non lo trova 
semplicemente perché l'ho rimesso in scatola a dormire, quindi se nulla è 
collegato significa che non lo uso e quindi i log dovrebbero mettersi in 
letargo e non crearsi in continuazione. Me ne accorsi solo perché in fase di 
deframmentazione disco trovavo ogni giorno questa cartella CIEPKI creante 
frammentazione e devo ammettere che mi ha dato molto fastidio questo 
comportamento.
OT: riguardo alla tua domanda #97 (posso scrivere solo perché ho ricevuto 
per email il tuo messaggio, ora non avendo il telefono con me non posso 
accedere a github per risponderti nel topic adeguato che hai appena aperto): 
è giusto che InfoCert ti invalidi la forma con CIE in quanto essa è "solo" 
FEA e non una FEQ, cioè al momento il Ministero dell'Interno non vuole 
competere con i provider privati che offrono firme qualificate a pagamento 
(tranne in Sardegna dove sono gratis via TS-CNS: beati loro!!!) e quindi il 
certificato rilasciato non è affidabile, o meglio lo è ma solo come FEA e 
neppure come FEA in generale ma solo come FEA nei confronti della Pubblica 
Amministrazione.
Se lo stesso file lo firmi (con la card InfoCert acquistata? in questo senso 
dici "con altra applicazione", altra rispetto a CIEID?) con app del provider 
ad es. InfoCert/Namirial...sì sarà reputata valida in quanto "vera FEQ" e 
non semplice FEA.
Comunque la CIE ora (e forse per moltissimo tempo in futuro) non è 
assolutamente in grado di generare firma che superi i vari test di 
validazione (InfoCert, PosteCert, Aruba, Adobe Acrobat PDF, ....), e questo 
a causa di convenzioni/mancate convenzioni, e NON per limite di 
tecnologia/chip/chiavi asimmetriche...). Scusa ancora per OT ma posso 
rispondere solo a questo 3d in quanto da me aperto e quindi mediante email 
da desktop.

**Comment by aantetomaso** [comment]
Prego riportare la discussione su forum.italia.it lasciando questo spazio solo per le issues da risolvere. Grazie.
